### ISSUE TITLE
#privacy : inform and opt-in about Google tracking 

### ISSUE THREAD

**Issue by Fil** [BusterLabs/Partyshare#15]
https://github.com/BusterLabs/Partyshare/blob/master/src/static/js/analytics.js

What exactly are you allowing google to track, and for what purposes?

Shouldn't users be informed, and allowed to opt-in tracking if they want to help you do whatever you need this for?

thanks! (very promising app!)

**Comment by bhstahl** [comment]
Hey @Fil, this was soley to see how people are using Partyshare in order to make a better product. It's firing events on how users use it, such as [copying a share link](https://github.com/BusterLabs/Partyshare/blob/2f20dc8f532a8d6396f9a92628cc3810f557ee9d/src/ui/components/FileListItem.jsx#L31-L34) vs [opening it directly](https://github.com/BusterLabs/Partyshare/blob/2f20dc8f532a8d6396f9a92628cc3810f557ee9d/src/ui/components/FileListItem.jsx#L46-L49). 

I do now see how that is a privacy concern, and not the intention of this project. First and foremost its about open and secure practices. I will remove the Google Analytics tracking until I build a better opt-in flow for any and all analytics.

Thanks for checking this project out! Would love any and all other feedback you have.

**Comment by Fil** [comment]
Thank you! (I'm sorry my message was a bit tone-deaf.)

Your app is great, very nice design, simple to understand and helps leverage the power of IPFS.

Since you've asked, here are a few comments :-)

- I would not personally recommend branding it as "sort of dropbox-like", it's quite different and people who search for a dropbox replacement would not find what they need here. Plus, Dropbox will die at some point, but IPFS won't. (Or so goes the story.)

- It would be great to be able to share a "folder" not only individual files, and to share files with their real names and extensions instead of just a plain hash. (The solution is to wrap the file into a folder, I think.)

- The great thing with IPFS is that if you rename a file it's hash doesn't change. However it's unclear in the app what happens if you change the contents of a file (I'm not sure of how the UI could reflect that? — maybe by writing `project-(version of [date]).odt` instead of `project.odt`, at least if we detect a change in contents

- Also, when you rename a file, the UI keeps displaying the older name, it could change and track the new name silently.

- Something is missing in the UI: how do you know that your file has been "shared" and you can now safely turn off the internet? I suppose it's hard to do, but knowing that the file is now safely out somewhere on at least 1 remote copy would be great. Also it would be a great for files that happen to be already up there, to see them transferred faster than light, Pied-Piper style.

(I can dispatch these in individual issues if you prefer)
